notebook/notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notebook_app.urls')),
]

notebook/notebook_app/urls.py
from django.urls import path
from .views import (NoteHomepageView, validate_new_note_view, NoteUpdateView, pinned_view, delete_note_view,

                    )

app_name = 'notes'

urlpatterns = [
    path('', NoteHomepageView.as_view(), name='home'),
    path('pinned/<int:pk>/', pinned_view, name='pinned'),
    path('validate-note-creation/', validate_new_note_view, name='validate_note_creation'),
    path('note/update/<int:pk>/', NoteUpdateView.as_view(), name='note_update'),
    path('note/delete/<int:pk>/', delete_note_view, name="delete_note"),

]

notebook/notebook_app/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField


COLORS = (
        ('a', 'yellow'),
        ('b', 'white'),
        ('c', 'green'),
        ('d', 'red'),
        ('e', 'blue')
    )


class Tags(models.Model):
    title = models.CharField(unique=True, max_length=240)

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:tag_update', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('notes:tag_delete', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        search_name = request.GET.get('search_name', None)

        qs = qs.filter(title__icontains=q) if q else qs
        qs = qs.filter(title__icontains=search_name) if search_name else qs
        return qs


class Note(models.Model):
    pinned = models.BooleanField(default=False)
    title = models.CharField(max_length=400)
    description = HTMLField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    date = models.DateField(blank=True, null=True)
    tag = models.ManyToManyField(Tags, blank=True)
    color = models.CharField(max_length=1, choices=COLORS, default='a')

    class Meta:
        ordering = ['-pinned', '-timestamp']

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:note_update', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        tags = request.GET.getlist('tag', None)
        if tags:
            tags_ = Tags.objects.filter(id__in=tags)
            qs = qs.filter(tag__in=tags_)
        qs = qs.filter(title__icontains=q) if q else qs
        return qs

notebook/notebook_app/forms.py
from django import forms

from .models import Tags, Note


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NoteForm(BaseForm, forms.ModelForm):

    class Meta:
        model = Note
        fields = ['pinned', 'color', 'title', 'tag', 'description']


class TagForm(BaseForm, forms.ModelForm):

    class Meta:
        model = Tags
        fields = '__all__'

notebook/notebook_app/views.py
from django.shortcuts import reverse, redirect, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

from django_tables2 import RequestConfig

from .models import Tags, Note
from .forms import NoteForm, TagForm
from .tables import TagsTable


@method_decorator(staff_member_required, name='dispatch')
class NoteHomepageView(ListView):
    template_name = 'notes/homepage.html'
    model = Note
    
    def get_queryset(self):
        qs = Note.objects.all()
        qs = Note.filters_data(self.request, qs)
        return qs

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = NoteForm()
        context['pinned_qs'] = self.object_list.filter(pinned=True)
        context['qs'] = self.object_list.filter(pinned=False)[:30]
        return context


@staff_member_required
def validate_new_note_view(request):
    form = NoteForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'New message added')
    return redirect(reverse('notes:home'))


@method_decorator(staff_member_required, name='dispatch')
class NoteUpdateView(UpdateView):
    form_class = NoteForm
    success_url = reverse_lazy('notes:home')
    template_name = 'notes/form.html'
    model = Note

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = self.success_url
        context['form_title'] = f'Επεξεργασια {self.object.title}'
        return context

    def form_valid(self, form):
        form.save()
        messages.success(self.request, f'Η σημειωση ανανεώθηκε!')
        return super().form_valid(form)


@staff_member_required
def pinned_view(request, pk):
    instance = get_object_or_404(Note, id=pk)
    instance.pinned = False if instance.pinned else True
    instance.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'), reverse('notes:home'))


@staff_member_required
def delete_note_view(request, pk):
    instance = get_object_or_404(Note, id=pk)
    instance.delete()
    messages.warning(request, 'Διαγραφηκε')
    return redirect(reverse('notes:home'))

notebook/notebook_app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% include 'include/css.html' %}
{% block extra_css %} {% endblock %}

<body class="">
  <div class="wrapper ">
    {% include 'include/navbar.html' %}
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="{{ request.path }}">{{ page_title }}</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form {% if action_url %} action="{{ action_url }}"  {% endif %}>
                <div class="input-group no-border">
                    <input name="q" type="text" value="{{ request.GET.q }}" class="form-control" placeholder="Create..."
                    
                    >
                    <div class="input-group-append">
                        <div class="input-group-text"><i class="nc-icon nc-zoom-split"></i></div>
                    </div>
                </div>
            </form>

          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-lg">

  <canvas id="bigDashboardChart"></canvas>
        </div> -->
       {% block content %}

       {% endblock %}

        {% if messages  %}
           <div class="modal" tabindex="-1" role="dialog" id="messageModal">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">Μύνημα</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <ul class="message">
                        {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                 {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

        {% endif %}
            <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <ul>
                <li>
                  <a href="#" target="_blank">Muinde J. Kivai</a>
                </li>
                <li>
                  <a href="#" target="_blank">Blog</a>
                </li>
                <li>
                  <a href="h#" target="_blank">Licenses</a>
                </li>
              </ul>
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script>, made with <i class="fa fa-heart heart"></i> by Muinde J. Kivai
              </span>
            </div>
          </div>
        </div>
      </footer>
        </div>

    </div>
  {% include 'include/js.html' %}
  {% block extra_js %} {% endblock %}
</body>

</html>

notebook/notebook_app/templates/include/css.html
{% load static %}

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Paper Dashboard 2 by Creative Tim
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/css/paper-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'assets/demo/demo.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'daterangepicker-master/daterangepicker.css' %}" />

</head>

notebook/notebook_app/templates/include/js.html
{% load static %}

<!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>

  <!-- Chart JS -->
  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/paper-dashboard.min.js' %}" type="text/javascript"></script>
  <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'assets/demo/demo.js' %}"></script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
      demo.initChartsPages();
    });
  </script>
<script type="text/javascript">
    $(window).on('load',function(){
        $('#messageModal').modal('show');
    });
</script>



    <script type="text/javascript" src="{% static 'daterangepicker-master/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'daterangepicker-master/daterangepicker.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            var start = moment().subtract(24, 'months');
            var end = moment().endOf('year');
            function cb(start, end) {
                $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            }

            $('#reportrange').daterangepicker({
                ranges: {
                   'Προηγουμενοι 12 μηνες': [moment().subtract(12, 'months'), moment()],
                   'Αυτη η χρονια': [moment().startOf('year'), moment().endOf('year')],
                   'Προηγουμενη Χρονια': [moment().startOf('days').subtract(1,'year'),  moment().endOf('year').subtract(1, 'year')],

                   'Σημερα': [moment(), moment()],
                   'Εχτες': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                   'Προηγουμενες 7 ημερες': [moment().subtract(6, 'days'), moment()],
                   'Προηγουμενες 30 μερες': [moment().subtract(29, 'days'), moment()],
                   'Αυτος ο Μηνας': [moment().startOf('month'), moment().endOf('month')],
                   'Προηγουμενος Μηνας': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                },
                startDate:start,
                endDate:end
            }, cb);

    cb(start, end);

});
</script>

notebook/notebook_app/templates/include/navbar.html
{% load static %}

<div class="sidebar" data-color="white" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="/" class="simple-text logo-mini">
        </a>
        <a href="{% url 'notes:home' %}" class="simple-text logo-normal">
         Note Demo
          <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{% url 'notes:home' %}">
              <i class="nc-icon nc-user-run"></i>
              <p>Notes</p>
            </a>
          </li>

        </ul>
      </div>
    </div>

notebook/notebook_app/templates/notes/form.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}

{% block extra_css %}
 {{ form.media }}
 <style>
    textarea.form-control{
        max-height: 600px;
        width:1800px;
    }
    #id_description {
        max-height: 600px;
        height:600px;
    }
    #id_tag {
        max-height: 250px;
        height:250px;
    }
 </style>
 {% endblock %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class='card'>
                    <div class='card-header'>
                        <h4>{{form_title}}</h4>
                        <!-- Large modal -->
                        <a href="{{ back_url }}" class="btn btn-warining pull-right">Back</a>
                    </div>
                     <div class="card-body">
                        <form method='post' class='form'>
                            {% csrf_token %}
                            {{ form }}
                            <br />
                            <button class='btn btn-success pull-right' type='submit'><i class='fa fa-save'></i></button> 
                        </form>
                     </card>
                    
                </div>
            </div>
            <div class="col-2"></div>
        </div>


        </div>

    </div>

{% endblock %}

notebook/notebook_app/templates/notes/homepage.html
{% extends 'dashboard.html' %}  {% load render_table from django_tables2 %}

{% block extra_css %}
    {{ create_form.media }}
    <style>
        textarea.form-control {
            max-height: 600px;
            width:1800px;
        }
        #id_description {
            max-height: 500px;
            height:500px;
        }
        #id_description_ifr {
            max-height: 500px;
            height:500px;
        }
        #id_tag {
            max-height: 150px;
            height:150px;
        }
    </style>
 
{% endblock %}

{% block content %}
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class='card'>
                    <div class='card-header'>
                        <h4>Notes</h4>

                    </div>
                    <div class='card-body'>
                        <div class='row'>
                            <div class='col-6'>
                            <!-- Large modal -->
                                <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bd-example-modal-lg">New Note</button>
                                <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Create</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body" style='height:700px; overflow-y: scroll;'>
                                             <form method='post' class='form' action='{% url "notes:validate_note_creation" %}'>
                                                {% csrf_token %}
                                                {{ create_form }}
                                                <br />
                                            <button type='submit' class='btn btn-primary'><i class='fa fa-save'></i> Save</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                        </div></div>
                            <div class='col-6'>
                                <form method='get'>
                                    <input name='q' class='form-control' type='text' placeholder='Search' />
                                    <button type='submit' class='btn btn-info'><i class='fa fa-search'> </i> </button>
                                    <a href='{{ request.path }}' style='color:red' class='pull-right btn btn-warning'><i class='fa fa-remove'> </i></a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class='row notes'> 
            <div class='col-12'><h5> Pinned </h5></div>
            {% for note in pinned_qs %}
                {% include 'notes/note_card.html' %}
            {% endfor %}
        </div>

        <div class='row notes'> 
            <div class='col-12'><h5> Rest notes </h5></div>
            {% for note in qs %}
                {% include 'notes/note_card.html' %}
            {% endfor %}
        </div>

        


    </div>

{% endblock %}

notebook/notebook_app/templates/notes/note_card.html
<div class='col-3'>
    <div class="card card-nav-tabs text-center" style=' border-top: 5px solid {{ note.get_color_display }};'>
        <div class="card-header card-header-primary">
            {% if note.pinned %}
                <a style='color:green' href="{% url 'notes:pinned' note.id %}"><i style='color:green' class='fa fa-thumb-tack'></i></a>
            {% else %}
                <a href="{% url 'notes:pinned' note.id %}"><i style='color:red' class='fa fa-thumb-tack'></i></a>
            {% endif %}
        </div>
        <div class="card-body">
            <h4 class="card-title">{{ note|safe }}</h4>
            <p class="card-text">{{ note.description|safe|truncatechars_html:50 }}</p>
        </div>
        <div class="card-footer text-muted">
            {% for tag in note.tag.all %} <a href='{{ request.path }}?tag={{ tag.id }}'><i class="fa fa-tag" aria-hidden="true"></i> {{ tag }}</a>  {% empty %} No tags{% endfor %}
            <br>
            <p class='text-muted'>Created {{ note.timestamp}} <p>
            <a href='{{ note.get_edit_url }}' style='color:blue' class='pull-left'><i class='fa fa-edit'> </i></a>
            <a onclick='return confirm("Εισαι σιγουρος;")' href='{% url "notes:delete_note" note.id %}' style='color:red' class='pull-right'><i class='fa fa-trash'> </i></a>
        </div>
    </div>
</div>